#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using the SIGKILL signal.

# Find the PID of the 7-highlander process
PID=$(pgrep -f "bash ./7-highlander")

# Send SIGKILL (signal 9) to the process
if [ -n "$PID" ]; then
    kill -9 "$PID"
fi
